version: '3.7'
networks:
  default:
    external:
      name: infra
services:
  jenkins-master:
    image: "zebrunner/jenkins-master:${TAG_JENKINS_MASTER}"
    container_name: jenkins-master
    env_file:
      - variables.env
    volumes:
     - "data-volume:/var/jenkins_home:rw"
    ports:
     - "8080:8080"
     - "50000:50000"
    restart: always
volumes:
  data-volume:

